### ISSUE TITLE
release 时会提示 [NOTIC] can't find dep resource 

### ISSUE THREAD

**Issue by cheft** [zyeeda/fis-muffin#2]
release 时会提示 [NOTIC] can't find dep resource ，只是提示，但不影响使用。是因为采用 fis-autoload插件导致的，向fis-autoload 发 pull request后再修复此问题。

**Comment by cheft** [comment]
向 fis-autoload 提交 pull request (https://github.com/hefangshi/fis-postpackager-autoload/pull/5)，后加入以下配置解决：

    settings: {
        postpackager: {
            autoload: {
                notice: {
                    exclude: [/_app.js/]
                }
            }
        }
    }

**Comment by luckymore** [comment]
哪里解决了。。。。呜呜😭[NOTIC] can't find dep resource [pages/adminverify]

 [NOTIC] can't find dep resource [pages/adminverify]

 [NOTIC] can't find dep resource [pages/distributemanager]

 [NOTIC] can't find dep resource [pages/distributemanager]

 [NOTIC] can't find dep resource [pages/enterprise]

 [NOTIC] can't find dep resource [pages/enterprise]

 [NOTIC] can't find dep resource [pages/index]

**Comment by tangrui** [comment]
你好 @luckymore 

请描述一下你的运行环境，比如 node, fis 的版本之类的，如果可以的话，最好能够提供一下你的代码库或者能够重现的代码，多谢！

**Comment by luckymore** [comment]
@tangrui 解决了，是因为require的文件里没有js文件，fis-conf.js没匹配到所以报错了。。
谢谢！
