### ISSUE TITLE
遇到错误，没太看懂，乱码

### ISSUE THREAD

**Issue by tcdona** [zyeeda/fis-muffin#3]
···
\muffin-demo (master)
mfn
'E:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

 Ω .............
 [NOTIC] can't find dep resource [bootstrap.css]

 [NOTIC] can't find dep resource [app]

 [NOTIC] can't find dep resource [bootstrap.css]

 [NOTIC] can't find dep resource [app]
 136ms

\muffin-demo (master)
λ mfn start
shutdown java process [29040]
checking java support : v1.7.0
checking php-cgi support : unsupported php-cgi environment
starting fis-server .... at port [8080]

 [NOTIC] browse http://127.0.0.1:8080/

···

**Comment by cheft** [comment]
是不是有中文路径，改个路径试试

**Comment by tcdona** [comment]
不是，能告诉我这里的 e:/program 最后可能指向了哪里吗？ 因为我运行的目录是 e:/work/p3/muffin-demo

**Comment by cheft** [comment]
这个有点像 fis 的问题，你使用 mfn open 打开目录看下在哪里。另外 [NOTIC] can't find dep resource [bootstrap.css] 应该是没有执行  bower install 吧

**Comment by tcdona** [comment]
额，我网络太破，bower install 一直失败。。。而且还要用到 bower 装 bootstrap 貌似文档没写啊

**Comment by tcdona** [comment]
我就是按照这里来的
https://github.com/cheft/muffin-demo
bower 相关的该怎么做？

**Comment by cheft** [comment]
不好意思，我想岔了，项目没用到 bower。第三方库是用 npm 管理的，执行 npm install 来安装库。npm install 安装成功了吗？或者你把整个库打个包发我邮箱 cn.cheft@gmail.com ，我看下。

**Comment by tangrui** [comment]
在 Windows 下，似乎是无法生成打包压缩后的 js 文件，dist/app.js 文件为空。但是没有出现楼主说的乱码的问题。

```
C:\Users\tangrui\muffin-demo>mfn


 Ω ..............
 [NOTIC] can't find dep resource [bootstrap.css]

 [NOTIC] can't find dep resource [bootstrap.css]
 827ms
```

而且从输出来看，`npm install` 以后任然会出现找不到资源的日志，但是在 Mac 上就没有这个问题。

**Comment by tcdona** [comment]
邮件已发

**Comment by cheft** [comment]
嗯，在抽时间看，貌似在windows上， npm包不一样，缺少东西，迟点发个版本。

**Comment by tcdona** [comment]
ok 那就期待稳定点的windows下版本吧 ~~
